# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: google/cloud-sdk
      
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            apt install -y python3-venv
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install --upgrade pip
            pip3 install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
      # run lints!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint


 
            
  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: service account key
          command: echo ${GCLOUD_SERVICE_KEY} > ${HOME}/sur.json
      - run:
          name: set gcloud command
          command: |
            gcloud auth activate-service-account --key-file=${HOME}/sur.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/region ${GOOGLE_COMPUTE_REGION}-a
      - run:
          name: deploy to app engine
          command: |
            gcloud app deploy app.yaml
        
             
                    
#Invoke jobs through workflows. Eg app will be built to dev unless branch selected is main
workflows:
  build:
    jobs:
      - build
      - deploy:
        filters:
          branches:
            only: main
