# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: google/cloud-sdk
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            apt install -y python3-venv
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install --upgrade pip
            pip3 install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      # run tests!
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make test
      # run lints!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint


      # GCP auth/ deployment
      - run:
          name: deploy to app engine
          command: |
            #echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            echo ${GCLOUD_SERVICE_KEY} > /tmp/sur.json
            gcloud auth activate-service-account --key-file=/tmp/sur.json
            rm /tmp/sur.json
            gcloud --quiet config set project qwiklabs-gcp-00-6a7638d1f745
            gcloud --quiet config set compute/zone us-west2
            gcloud app deploy


